### ISSUE TITLE
Migrate openbet.io/edit to Next 13 app dir

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#1073]
**What would you like to be able to do? Please describe.**
Area pages and the landing page have been migrated to Next 13 app dir.  Let's migrate [pages/edit](https://github.com/OpenBeta/open-tacos/blob/develop/src/pages/edit/index.tsx).

### Todo:
- [x] create `edit` dir under src/app
- [x] create `page.tsx` in the edit dir
- [x] copy the content from the old [src/pages/edit/index.tsx](https://github.com/OpenBeta/open-tacos/blob/develop/src/pages/edit/index.tsx) to src/app/page.tsx
- [x] move getChangeHistoryServerSide() in **getStaticProps()** to the main Page component.  Get rid of getStaticProps()

You may need to mark the file with 'use client' for now.  See https://nextjs.org/docs/pages/building-your-application/upgrading/app-router-migration#step-4-migrating-pages

**Comment by btmccord** [comment]
I'll take this on

**Comment by btmccord** [comment]
I am not sure that I am doing this right...

After following your to-dos adding 'use clients' gives me a error for having async/await in a client component. Not adding it causes compiling to fail for using next/router in a server component. I assume we need to update these to use the newer next/navigation routing for this to work?

![Screenshot 2024-01-13 101918](https://github.com/OpenBeta/open-tacos/assets/24865286/59836fcf-5a7b-4e38-9368-9fc205918522)


The only way that was successful was very similar to the Next migration guide. I made two files (page.tsx & EditsContent.tsx) under src/app/edit. Page is a server component and basically just calls getChangeHistoryServerSide and passes the history to EditsContent which is a client component (has 'use client') and contains the code previously in the Page component.

**Comment by vnugent** [comment]
Thanks for taking on this one. There are a few things that automagically work by convention in Next 13.  One of them is  shared layout.  You can remove the import Layout in page.tsx.  Next 13 will put all **page.tsx** files under `src/app` in the layout in https://github.com/OpenBeta/open-tacos/blob/develop/src/app/layout.tsx (you don't have to explicitly import the layout file).

**Comment by vnugent** [comment]
An example page.tsx: https://github.com/OpenBeta/open-tacos/blob/develop/src/app/area/%5B%5B...slug%5D%5D/page.tsx

**Comment by btmccord** [comment]
Got it. 

Removing the Layout element fixes the compile error.

It now renders with a different header. I assume this is what we want?

![Screenshot 2024-01-13 112702](https://github.com/OpenBeta/open-tacos/assets/24865286/88043a62-9b3d-4e60-834b-5dd83d1e5ecb)
![Screenshot 2024-01-13 112716](https://github.com/OpenBeta/open-tacos/assets/24865286/2cfbc031-b5ec-4a51-af95-90f20f6b17c3)

**Comment by vnugent** [comment]
Yes. Should be the same as the main page (openbeta.io) and all the area pages
