### ISSUE TITLE
Improve mobile/tablet support

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#261]
- [x] Create separate navbar for mobile and desktop #251 
- [x] Make map full screen on mobile #260 
- [x] Fix index page margin
- [x] Improve Crag card view
- [x] Fix widescreen issue #262 
- [x] Search box should be wider on mobile #264
