### ISSUE TITLE
Setup authentication

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#298]
We need to add site-wide authentication for 2 important upcoming features:
- Photo uploading #176
- Adding/editing content #177 

### Tasks:
- [ ] Integrate https://github.com/nextauthjs/next-auth
- [ ] Pick an Auth provider (Auth0, Okta, etc)
- [ ] Create a simple login page

We want to be able to allow authenticated users to call backend APIs so something like OAuth + JWT could work.
