### ISSUE TITLE
Latest release: Milestone 4  

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#338]
Proposed work for M4 (due Aug 1)

### Content Edit/Add
- [ ] https://github.com/OpenBeta/open-tacos/issues/177
     * [x] https://github.com/OpenBeta/openbeta-graphql/issues/81
     * [ ] https://github.com/OpenBeta/openbeta-graphql/issues/88
     * [ ] https://github.com/OpenBeta/open-tacos/issues/429
- [x] https://github.com/OpenBeta/open-tacos/issues/409
- [ ] Users can update isDestination flag
 
### User Profile
- [ ] https://github.com/OpenBeta/open-tacos/issues/410
- [x] https://github.com/OpenBeta/open-tacos/issues/434
- [ ] - [ ] https://github.com/OpenBeta/open-tacos/issues/426

###  Search & Filters
   - [x] https://github.com/OpenBeta/open-tacos/issues/255
      - [ ] https://github.com/OpenBeta/openbeta-graphql/issues/83

### Climb and area page improvement
   - [ ] Area page improvement.  Issue TBD
   - [x] https://github.com/OpenBeta/open-tacos/pull/369

### Photos
   - [x] https://github.com/OpenBeta/open-tacos/issues/443
   - [ ] https://github.com/OpenBeta/open-tacos/issues/348
   - [x] https://github.com/OpenBeta/open-tacos/issues/322 
   - [ ] https://github.com/OpenBeta/open-tacos/issues/370
   - [ ] https://github.com/OpenBeta/open-tacos/issues/386
   - [x] https://github.com/OpenBeta/open-tacos/pull/400
   - [x] https://github.com/OpenBeta/open-tacos/issues/371
   - [x] https://github.com/OpenBeta/open-tacos/issues/340
   - [x] https://github.com/OpenBeta/open-tacos/issues/349
   - [x] https://github.com/OpenBeta/open-tacos/issues/343
   - [x] https://github.com/OpenBeta/open-tacos/issues/339 
   - [x] https://github.com/OpenBeta/open-tacos/pull/347

### Auth
   - [ ] https://github.com/OpenBeta/open-tacos/issues/317
   - [x] https://github.com/OpenBeta/open-tacos/issues/318 
 
### Legal
   - [ ] https://github.com/OpenBeta/open-tacos/issues/307 
   - [ ] Update Tos Page
   - [ ] Link to ToS from Footer
   - [ ] Link to ToS from Login/signup page

### Misc
- [x] https://github.com/OpenBeta/open-tacos/issues/385
- [x] https://github.com/OpenBeta/open-tacos/pull/412
- [x] https://github.com/OpenBeta/open-tacos/issues/408
- [x] https://github.com/OpenBeta/open-tacos/issues/404
- [x] https://github.com/OpenBeta/open-tacos/issues/415
- [x] https://github.com/OpenBeta/open-tacos/issues/431
- [x] https://github.com/OpenBeta/open-tacos/issues/416
- [x] https://github.com/OpenBeta/open-tacos/issues/438

### Bugs
- [x] https://github.com/OpenBeta/open-tacos/pull/367
- [x] https://github.com/OpenBeta/open-tacos/issues/358
- [x] https://github.com/OpenBeta/open-tacos/issues/353
- [x] https://github.com/OpenBeta/open-tacos/issues/359
- [x] https://github.com/OpenBeta/open-tacos/pull/356
- [x] https://github.com/OpenBeta/open-tacos/issues/375
- [x] https://github.com/OpenBeta/open-tacos/issues/389
- [x] https://github.com/OpenBeta/open-tacos/issues/399
- [x] https://github.com/OpenBeta/open-tacos/issues/382
- [x] https://github.com/OpenBeta/open-tacos/issues/428
- [ ] https://github.com/OpenBeta/open-tacos/issues/376
- [ ] https://github.com/OpenBeta/open-tacos/issues/427
- [ ] https://github.com/OpenBeta/open-tacos/issues/436

**Comment by vnugent** [comment]
Previous release: https://github.com/OpenBeta/open-tacos/issues/277
