### ISSUE TITLE
Display FA badge on router developer profile

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#426]
### Use case
As a community member I want to recognize FAists for their contribution.   Users can self-assign the FA role.

### Todo
- [ ] Come up with an icon for the FA badge (a laurel, a drill/hammer?)
- [ ] Add a checkbox to profile edit component
- [ ] Display the badge on the profile page
