### ISSUE TITLE
Start here: 🐿️ Milestone 5 

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#446]
Please suggest what you think we should work on next.  

### Offline support
- [ ] https://github.com/OpenBeta/open-tacos/issues/454
   - [ ] https://github.com/OpenBeta/open-tacos/issues/493

### Content edit
   - [x] https://github.com/OpenBeta/open-tacos/issues/429
   - [x] https://github.com/OpenBeta/open-tacos/issues/490
   - [x] https://github.com/OpenBeta/open-tacos/issues/495
   - [x] https://github.com/OpenBeta/open-tacos/issues/496
   - [x] https://github.com/OpenBeta/open-tacos/issues/541
   - [ ] User can add a crag/boulder + climbs
   - [ ] User can remove climbs from a crag/boulder
   - [x] User can remove an empty area https://github.com/OpenBeta/open-tacos/issues/538
   - [x] https://github.com/OpenBeta/open-tacos/pull/530
### Photos
   - [x] https://github.com/OpenBeta/open-tacos/issues/348
   - [x] https://github.com/OpenBeta/open-tacos/issues/370
   - [ ] https://github.com/OpenBeta/open-tacos/issues/386
   - [ ] User can flag an inappropriate photo
   - [ ] Admins can disable a photo
   - [x] https://github.com/OpenBeta/open-tacos/issues/464
       - [x] https://github.com/OpenBeta/open-tacos/issues/542

### User experience
- [x] https://github.com/OpenBeta/open-tacos/issues/457
- [ ] https://github.com/OpenBeta/open-tacos/issues/468
- [x] https://github.com/OpenBeta/open-tacos/issues/447
   - [ ] https://github.com/OpenBeta/open-tacos/issues/525
- [x] https://github.com/OpenBeta/open-tacos/issues/518
   - [x] https://github.com/OpenBeta/open-tacos/issues/480
- [ ] Display Quality index on climb page
- [ ]  Display Quality index on area page

### Search improvements
   - [ ] Add search result summary icons (Issue TBD) 
   - [x] https://github.com/OpenBeta/openbeta-graphql/issues/83
   - [ ] https://github.com/OpenBeta/openbeta-graphql/issues/100
   - [ ] Sort search result by quality index
   
### Dev & Ops
   - [x] https://github.com/OpenBeta/open-tacos/issues/474
   - [ ] https://github.com/OpenBeta/open-tacos/issues/455
   - [ ] https://github.com/OpenBeta/open-tacos/issues/317
   - [x] https://github.com/OpenBeta/open-tacos/issues/471
   - [x] https://github.com/OpenBeta/open-tacos/issues/489

### Bugs
- [x] https://github.com/OpenBeta/open-tacos/issues/532 (P2)
- [ ] https://github.com/OpenBeta/open-tacos/issues/462
- [x] https://github.com/OpenBeta/open-tacos/issues/376
- [x] https://github.com/OpenBeta/open-tacos/issues/427
- [ ]  https://github.com/OpenBeta/open-tacos/issues/436
- [x] https://github.com/OpenBeta/open-tacos/issues/485

### General
- [x] https://github.com/OpenBeta/open-tacos/issues/475
- [x] https://github.com/OpenBeta/open-tacos/issues/405

**Comment by vnugent** [comment]
Milestone 4 https://github.com/OpenBeta/open-tacos/issues/338
