### ISSUE TITLE
Users can't edit

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#550]
In order to submit an edit the backend requires a custom 'editor' role in the JWT token.   

### Need decision

Do we want to set a minimum requirement such as email must be verified before granting the permission?

### Todos
- [ ] Ask viet at openbeta.io for Auth0 dev credential
- [x] Add code to  Auth0 login action (on Auth0.com) to give the user `editor` role
- [x] Save post login action in https://github.com/OpenBeta/open-tacos/blob/develop/AuthProvider/postLoginAction.js
