### ISSUE TITLE
🌵 Milestone 6

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#574]
What should we work on next?

### Offline support
- [ ] https://github.com/OpenBeta/open-tacos/issues/454
   - [ ] https://github.com/OpenBeta/open-tacos/issues/493

### Content edit
   - [x] https://github.com/OpenBeta/open-tacos/issues/496
   - [x] Users can view edit history of an area https://github.com/OpenBeta/open-tacos/pull/603
   - [x] https://github.com/OpenBeta/open-tacos/issues/550
   - [x] https://github.com/OpenBeta/open-tacos/issues/540
   - [x] https://github.com/OpenBeta/open-tacos/issues/585
   - [x] https://github.com/OpenBeta/open-tacos/issues/606

### Photos
   - [x] https://github.com/OpenBeta/open-tacos/issues/386
   - [ ] User can flag an inappropriate photo
   - [ ] Admins can disable a photo
   - [x] https://github.com/OpenBeta/open-tacos/issues/500
   - [x] https://github.com/OpenBeta/open-tacos/issues/616

### User experience
- [ ] https://github.com/OpenBeta/open-tacos/issues/525
- [ ] https://github.com/OpenBeta/open-tacos/issues/468
- [ ] Display Quality index on climb page
- [ ]  Display Quality index on area page
- [x] https://github.com/OpenBeta/open-tacos/issues/499
- [ ] https://github.com/OpenBeta/open-tacos/issues/582

### Search improvements
   - [x] https://github.com/OpenBeta/open-tacos/issues/610
   - [x] Add search result summary icons (Issue TBD) 
   - [ ] https://github.com/OpenBeta/openbeta-graphql/issues/100
   - [ ] Sort search result by quality index
   
### Dev & Ops
   - [ ] Investigate/move DB seed jobs to function to reduce hosting costs
   - [ ] https://github.com/OpenBeta/open-tacos/issues/455
   - [ ] https://github.com/OpenBeta/open-tacos/issues/317

### Bugs
- [x] https://github.com/OpenBeta/open-tacos/issues/614
- [x] https://github.com/OpenBeta/open-tacos/issues/565
- [ ] https://github.com/OpenBeta/open-tacos/issues/520
- [x] https://github.com/OpenBeta/open-tacos/issues/580
- [x] https://github.com/OpenBeta/open-tacos/issues/578
- [x] https://github.com/OpenBeta/docs.openbeta.io/issues/14
- [x] https://github.com/OpenBeta/open-tacos/issues/584
- [x] https://github.com/OpenBeta/open-tacos/issues/599
- [ ] https://github.com/OpenBeta/open-tacos/issues/617

## Milestones
- next: TBD
- previous https://github.com/OpenBeta/open-tacos/issues/446

**Comment by siman4457** [comment]
Feature suggestion:
Add filters to the "New Tags" and "Popular" pages that allow users to find routes in their area or a specific area quickly.
