### ISSUE TITLE
Milestone 7

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#634]
# Milestone 7

#### Editing
- [x] https://github.com/OpenBeta/open-tacos/issues/666
- [ ] https://github.com/OpenBeta/open-tacos/issues/667
- [x] https://github.com/OpenBeta/open-tacos/issues/633
- [x] https://github.com/OpenBeta/open-tacos/issues/644
- [x] https://github.com/OpenBeta/open-tacos/issues/386
- [ ] https://github.com/OpenBeta/open-tacos/issues/661

#### Enhancements
- [x] https://github.com/OpenBeta/open-tacos/issues/686
- [x] https://github.com/OpenBeta/open-tacos/issues/387 followup
- [ ] https://github.com/OpenBeta/open-tacos/issues/645
- [x] https://github.com/OpenBeta/open-tacos/issues/675
- [x] https://github.com/OpenBeta/open-tacos/issues/685
---

### Bugs
- [x] https://github.com/OpenBeta/open-tacos/issues/635
- [x] https://github.com/OpenBeta/open-tacos/issues/629
- [x] https://github.com/OpenBeta/open-tacos/issues/626
- [x] https://github.com/OpenBeta/open-tacos/issues/346
- [x] https://github.com/OpenBeta/open-tacos/issues/626
- [x] https://github.com/OpenBeta/open-tacos/issues/688
- [x] https://github.com/OpenBeta/open-tacos/issues/692
- [ ] https://github.com/OpenBeta/open-tacos/issues/631
- [ ] https://github.com/OpenBeta/open-tacos/issues/617
- [ ] https://github.com/OpenBeta/open-tacos/issues/575
- [x] https://github.com/OpenBeta/open-tacos/issues/678
- [x] https://github.com/OpenBeta/open-tacos/issues/701

### Chores
- [x] https://github.com/OpenBeta/open-tacos/issues/679
- [ ] https://github.com/OpenBeta/open-tacos/issues/656

---
M6: https://github.com/OpenBeta/open-tacos/issues/574
