### ISSUE TITLE
Rotate mapbox key

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#679]
Our Mapbox API use has been low, $0 bill each month.  For the month of Jan 2023 I got a bill for $51  (still need to investigate further). 

### Todo
- [x] Rotate API key
- [x] Restrict API key to openbeta.io domain 
- [x] Ask mapbox for nonprofit discount
