### ISSUE TITLE
Milestone 8

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#716]
## Editing
- [x] https://github.com/OpenBeta/open-tacos/issues/715
- [x] https://github.com/OpenBeta/open-tacos/issues/725
- [ ] https://github.com/OpenBeta/open-tacos/issues/662
- [ ] https://github.com/OpenBeta/openbeta-graphql/issues/213 (P2)
- [ ] https://github.com/OpenBeta/open-tacos/issues/667
- [ ] https://github.com/OpenBeta/openbeta-graphql/issues/233
- [ ] https://github.com/OpenBeta/sandbag/issues/80

## LCO Pilot (epic https://github.com/OpenBeta/open-tacos/issues/681)
- [x] Mockup for demoing: https://github.com/OpenBeta/open-tacos/pull/722
Tasks TBD

## Enhancements
- [x] https://github.com/OpenBeta/open-tacos/issues/749
- [ ] https://github.com/OpenBeta/open-tacos/issues/645
- [x] https://github.com/OpenBeta/open-tacos/issues/721
- [x] https://github.com/OpenBeta/open-tacos/issues/733
- [x] https://github.com/OpenBeta/open-tacos/issues/746
- [ ] https://github.com/OpenBeta/open-tacos/issues/750

## Bug
- [ ] https://github.com/OpenBeta/open-tacos/issues/631
- [ ] https://github.com/OpenBeta/open-tacos/issues/617
- [ ] https://github.com/OpenBeta/open-tacos/issues/575
- [x] https://github.com/OpenBeta/open-tacos/issues/755

## Chores
- [ ] https://github.com/OpenBeta/open-tacos/issues/656
- [x] https://github.com/OpenBeta/open-tacos/issues/738
- [x] https://github.com/OpenBeta/open-tacos/issues/749

Previous milestone https://github.com/OpenBeta/open-tacos/issues/634
