### ISSUE TITLE
Email validation in user signup flow

### ISSUE THREAD

**Issue by actuallyyun** [OpenBeta/open-tacos#746]
**What would you like to be able to do? Please describe.**

After signing up, I was prompted to check my email to validate my email address. After clicking on the link in my email, I was directed to this url `https://openbeta.us.auth0.com/u/email-verification?ticket=dGXPhgEpgEcGbJ1GMgjGc5zGdiCHBlrl#`. A success message was shown which was great. 

It would be nice to be redirected to sign in page or the main page after this though. 
![Screenshot 2023-03-22 at 15 19 03](https://user-images.githubusercontent.com/87448230/226933328-31563f29-d583-4b53-b588-be2af613917a.png)

**How important is this to you** (Please pick one)
Nice-to-have

**Comment by vnugent** [comment]
@all-contributors add @actuallyyun for ideas

**Comment by actuallyyun** [comment]
Hi @vnugent  I would like to work on this as my first issue if this sounds good to you.

**Comment by vnugent** [comment]
> Hi @vnugent I would like to work on this as my first issue if this sounds good to you.

Definitely.  One thing though, we use Auth0.com as our identity/authentication provider.   I'm not sure if we have control over that dialog unless we set up a custom email provider in Auth0 dashboard (we're currently using their free email service).  

https://auth0.com/docs/customize/email

Send me an email (viet at openbeta dot io) and I'll reply with additional API keys and give you access to the Auth0 test instance.  

IMO first PR should be fun.  In my experience Auth0 docs can be very confusing and sometimes it requires getting help on [their forum](https://community.auth0.com/). Do you want to do a bit of investigation to see if it's possible to redirect the user?

**Comment by actuallyyun** [comment]
yeah good point, I will look into their docs and see if it's possible.

**Comment by actuallyyun** [comment]
This seems to be one solution to this: https://community.auth0.com/t/need-to-update-the-redirect-url-for-password-reset/9626  It doesn't require code change, but configurations in `AuthO` settings.

**Comment by actuallyyun** [comment]
@vnugent If you could share the `Auth0` account, I could go in and try to fix this.

**Comment by vnugent** [comment]
> @vnugent If you could share the `Auth0` account, I could go in and try to fix this.

email me (viet at openbeta dot io) and I'll reply with additional API keys, etc

**Comment by actuallyyun** [comment]
Hey @vnugent After some digging in their docs, I think one solution is to config a default login route, then their universal login flow will add this to the email validation result, and the user can click and get redirected to the login page.
This is what their docs say:

>  **Email verification
> 
> After a user clicks the email verification link, they'll be redirected to a page that will confirm that their email is verified. If the default login route is configured, users will be able to click a button and get redirected to it.

Another related entry:

> ****Complete email verification flow****
> 
> As part of the signup process, users get an email to verify their email address. If they click on the link, they will land on a page that says that the email was verified, with a button to go back to the application. When clicked, users will be redirected to the login page, and if they already have a valid session, they'll end up being redirected to the application.
> 
> This behavior only happens when the New Universal Login Experience is enabled. In Classic mode, you need to configure the redirect URL in the Verification Email template.

From what I understood, opentaco is already using their _New Universal Login Experience_, so I think we just have to config the default login route. 

[Here is the documentation for doing it ](https://auth0.com/docs/authenticate/login/auth0-universal-login/configure-default-login-routes)

However, I am not sure I understood this part:

> The login_url should point to a route in the application that ends up redirecting to Auth0's /authorize endpoint, e.g. https://mycompany.org/login. Note that it requires https and it cannot point to localhost. login_url can include query parameters and a URI fragment.

What is this endpoint in the open taco project? I saw that you have `pages/auth/signin` route, but this shows a login with `Auth0` link. Perhaps this endpoint is not what they ask for. Do you know which endpoint might meet their requirements for redirecting to work?

**Comment by vnugent** [comment]
@actuallyyun Can you try with "https://stg.openbeta.io/auth/signin" and see it works?  It won't work for dev env but at least we can confirm if the link shows up on the email verified screen.

>  I saw that you have pages/auth/signin route, but this shows a login with Auth0 link. Perhaps this endpoint is not what they ask for. Do you know which endpoint might meet their requirements for redirecting to work?

I think we can improve that page adding a `useEffect()` to automatically send users to auth0.

**Comment by actuallyyun** [comment]
When I tried to add the url to the field, it shows `Error!You don't have permissions to access the resource` 😢  It's in the `dashboard`=>`Applications`

**Comment by vnugent** [comment]
> When I tried to add the url to the field, it shows `Error!You don't have permissions to access the resource` 😢 It's in the `dashboard`=>`Applications`

Strange because you and I have the same `admin` role.  

Anyway, I updated the OpenTacos (dev) with the url.  Can you test on staging?  https://stg.openbeta.io

**Comment by actuallyyun** [comment]
hmm it show `404` , and this is the url
`https://stg.openbeta.io/result_page?supportSignUp=true&supportForgotPassword=true&message=Your%20email%20was%20verified.%20You%20can%20continue%20using%20the%20application.&success=true&code=success`  it seems like `Auth0` did redirect but the url it redirected to is not found.

**Comment by vnugent** [comment]
AH! I think I got it now.

Once you click the email, Auth0 will mark the email/account as "validated" and redirect you back to the app url + `/result_page?...`.  You can customize the url if you set up our own stmp email provider.  In our case we don't have it, so Auth0 will use the default template which uses `result_page`.

They mention it in bullet #4 https://auth0.com/docs/customize/email/email-templates#configure-template-fields

We're seeing 404 because result_page doesn't exist in our project.

some ideas to move forward:

- [ ] in your dev env, create our own `/src/pages/result_page.tsx` (make a copy of `verify-request.tsx` and rename it)
- [ ] test to see if a new user sees this page after clicking on the verification request email
- [ ] if it works we can come up with a plan, what to put in the new page 

thank you!

**Comment by actuallyyun** [comment]
Cool I will give it a try!

**Comment by actuallyyun** [comment]
It did not work in dev env, it still redirected me to  `https://stg.openbeta.io/result_page`. Since the change I made is local,` result_page` dose not exist in the staging product.

This redirect behaviour is defined here :https://manage.auth0.com/dashboard/us/dev-fmjy7n5n/templates
![Screenshot 2023-03-27 at 17 42 58](https://user-images.githubusercontent.com/87448230/227992561-c0c4c5cb-1a45-4948-a85b-5ad141e768da.png)

> The application.callback_domain variable will contain the origin of the first URL listed in the application's Allowed Callback URL list. This lets you redirect users to a path of the application that triggered the action by using a syntax like this:
{{ application.callback_domain }}/result_page

> Note that while the variable is called callback_domain, it is really an origin, so it includes the protocol in addition to the domain, e.g. https://myapp.com.
> 
> If your application has multiple Allowed Callback URLs configured, Auth0 will use the first URL listed. You can also provide a default origin using Liquid syntax:
> 
> {{ application.callback_domain | default: "https://my-default-domain.com" }}/result_page
> 
> 

However though, when I tested again with the released product, this is the url after validation: https://openbeta.io/auth/verify-request?session_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzk5MzE4ODIsImlzcyI6Im9wZW5iZXRhLnVzLmF1dGgwLmNvbSIsInN1YiI6ImF1dGgwfDY0MjFiOWU5MzdhNzU1MTdjMmRjNzJkNSIsImV4cCI6MTY3OTkzMjc4MiwiaXAiOiIxODUuMTY1LjI1My4xNjUiLCJlbWFpbCI6ImlyZW5laml5dW5AZ21haWwuY29tIn0.PCBVRsiz2rjeYC_vttCjBd8UmD9GCoD94X9J7HFUhUA&state=hKFo2SBhbVREQVZiTktxVXRMbGJPdWtocEdtcm5sTmFNTEhwNaFuqHJlZGlyZWN0o3RpZNkgbjdxX1Y3RFNZTkhIaGd4ZTdLZV9SMUphZF93VktXT0ujY2lk2SBHT2pVMHQ3amNzUERyMVlkN09yVEtPeXdZeWd5UzF0TA

Another question, in the `dashboard>applications` field, there are quite a few applications. which one is which product?

**Comment by vnugent** [comment]
I did some additional testing in staging and prod, and can confirm the following behaviors:
- Auth0 verification email behaves differently depending on whether or not you specify an Application Login URI (Dashboard --> Apps --> OpenBeta (dev))
- When you provide a url, it will redirect to **Direct To** if a value is specified (https://auth0.com/docs/customize/email/email-templates#configure-template-fields)

> It did not work in dev env, it still redirected me to https://stg.openbeta.io/result_page. Since the change I made is local, result_page dose not exist in the staging product.

This is the correct behavior. I'm not sure if you can redirect to http://localhost in local dev env.  It will work correctly in staging and production.

**Comment by actuallyyun** [comment]
I see. Wanna make sure I understood it correctly.

So when **Application Login URI** is specified(does it matter which one?), in openbeta's case, its `https://stg.openbeta.io/auth/signin`, it redirects to the **Direct To** value which is `{{ application.callback_domain }}/result_page` . Then ` application.callback_domain` will look at the application's **Allowed Callback URL** list and use the first match it finds. If it's `localhost` domain, it should redirect the user to `locahost/result_page`. 

Since you have confirmed the behaviors, how should we move forward with this ? 

**update**
localhost does not work because the "Become a contributor" entry point points to the staging domain.

**Comment by vnugent** [comment]
When you were testing did you rearrange the list of **Allowed Callback URLs**?  I moved `http://localhost:300` to the front and was redirected to localhost:3000/result_page by clicking on the email link.

I'm wondering it'd do that in staging (we want it to send users to staging instead).

Anyway, you can proceed as follows: 

**Part 1: test new post-verified, welcome page**
- [ ] in your dev env, create our own /src/pages/result_page.tsx (make a copy of verify-request.tsx and rename it)
- [ ] test locally to see if a new user sees this page after clicking on the verification request email
- [ ] open a PR and we can test in staging

**Part 2: update the current `/src/pages/auth/signin.tsx`** to send users directly to Auth0 in `useEffect()` if they're not logged in (as recommended per Auth0 docs).

Example:

```javascript

export default function Page (): JSX.Element {
  const session = useSession()

  useEffect(() => {
    if (session.status === 'unauthenticated') {
      void signIn('auth0', { callbackUrl: '/api/user/me' })// send users to Auth0 login screen
    }
    if (session.status === 'authenticated') {
      void router.push('/api/user/me')
    }
  }, [session])


  return (
   <div>Please waiting...</div>
  )
}
```
Hope this makes sense.  Let me know if you have any questions.

**Comment by actuallyyun** [comment]
Thanks for the reply.
I was just wondering, why don't we just redirect user to `signin` page , instead of `result_page`, I think we could just change `{{ application.callback_domain }}/result_page` to `{{ application.callback_domain }}/auth/signin`

**Comment by actuallyyun** [comment]
> When you were testing did you rearrange the list of **Allowed Callback URLs**? I moved `http://localhost:300` to the front and was redirected to localhost:3000/result_page by clicking on the email link.

same behaviour when I just tested, now it goes to localhost.

**Comment by vnugent** [comment]
I decided not to introduce the result_page for the time being (more work for us to design the new page).  We can add it in the future when we have more time and resources to improve new user onboarding.

With some config changes in Auth0 dashboard (documented below) and your update to the login page, when the user clicks on the magic link they will be taken to the confirmation screen **with a button taking them to the site.**  The button didn't exist before.

I'm glad we're able to get to the bottom of this.  Thank you for your help!

<img width="425" alt="Screenshot 2023-04-01 at 6 57 12 PM" src="https://user-images.githubusercontent.com/3805254/229304420-ccdf388a-8196-4a8b-9b82-c1d6fc3d3cda.png">

---

### Auth0 config how-tos:
1.  Specify login url 
<img width="796" alt="Screenshot 2023-04-01 at 6 55 57 PM" src="https://user-images.githubusercontent.com/3805254/229304646-37c1e1b5-6b3c-47df-9147-52b57f1ad0e0.png">

2.  Enable email verification template but clear out the Direct to field

<img width="499" alt="Screenshot 2023-04-01 at 6 51 05 PM" src="https://user-images.githubusercontent.com/3805254/229304687-6a9e6f57-5033-484d-9b77-e15e33d3fed7.png">

**Comment by actuallyyun** [comment]
Nice low cost high value solution! Happy to help and thanks for helping me figure it out.
