### ISSUE TITLE
🌱 Start here ➜ Milestone 9

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#780]
A list of milestone 9 issues

Previous milestone: https://github.com/OpenBeta/open-tacos/issues/716

###  LCO initiative
- [x] https://github.com/OpenBeta/open-tacos/issues/764
- [x] https://github.com/OpenBeta/open-tacos/issues/763
- [x] https://github.com/OpenBeta/open-tacos/issues/779
- [x] #792 
- [x] #779 

### Editing
- [x] https://github.com/OpenBeta/open-tacos/issues/662
- [x] https://github.com/OpenBeta/openbeta-graphql/issues/213 (P2)
- [x] https://github.com/OpenBeta/open-tacos/issues/667
- [ ] https://github.com/OpenBeta/openbeta-graphql/issues/233
- [ ] https://github.com/OpenBeta/sandbag/issues/80

### Photos
- [x] https://github.com/OpenBeta/open-tacos/issues/791

## Bug
- [x] https://github.com/OpenBeta/open-tacos/issues/631
- [x] https://github.com/OpenBeta/open-tacos/issues/617
- [x] https://github.com/OpenBeta/open-tacos/issues/575
- [x] https://github.com/OpenBeta/open-tacos/issues/793
- [x] https://github.com/OpenBeta/open-tacos/issues/826

## Chores
- [ ] https://github.com/OpenBeta/open-tacos/issues/656
- [x] https://github.com/OpenBeta/open-tacos/issues/794

### Enhancements
- [x] https://github.com/OpenBeta/open-tacos/issues/748

**Comment by vnugent** [comment]
@all-contributors add @shyamtawli for code
