### ISSUE TITLE
Refactor username update to work with new profile API

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#830]
### Important: New user signup is temporarily disabled to prevent introducing consistent data

**What would you like to be able to do? Please describe.**

I'm introducing a new [user profile API](https://github.com/OpenBeta/openbeta-graphql/pull/290) in the backend to incrementally migrate user profile data to our own db.  For this issue, create a new username update screen that uses the new get/set username API.

Related:
- https://github.com/OpenBeta/open-tacos/issues/718
- https://github.com/OpenBeta/open-tacos/issues/575
- https://github.com/OpenBeta/openbeta-graphql/issues/202 

**How important is this to you** (Please pick one)

- Important

### Todos
- [x] Create a new M2M action to add custom claim `uuid`
- [ ] Create a new get access token API
- [x] Create a new username update screen
