### ISSUE TITLE
Update brand font files

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#934]
**What would you like to be able to do? Please describe.**
Update font files.  Our friends at [Vectro Type Foundry](https://www.vectrotype.com/vctr-mono) has just updated the fonts with improved support for vertical spacing.

##Todo
- [x] Email viet at openbeta dot io for font files
- [x] Replace existing files at https://github.com/OpenBeta/open-tacos/tree/develop/public/fonts
- [x] Update file name (v0.12 -> v0.13) at https://github.com/OpenBeta/open-tacos/blob/develop/public/fonts/fonts.css

**How important is this to you** (Please pick one)
- Nice-to-have

**Comment by hawkishpolicy** [comment]
I can jump on this.

**Comment by hawkishpolicy** [comment]
Viet,

The new font files are OTF vs WOFF. Want the file format in .CSS file changed as well?

The file names from the new VCTRMono .zip does not include ".13"...should I make the URL in the .css match the existing file name of the new font file or update both the font file name and .css to include ".13"

**Comment by vnugent** [comment]
Please use the new font file name and extension
